name: 'tftools'
description: 'Install terraform tools'
inputs:
  tfenv-version:
    description: 'Version of tfenv to install'
    required: false
    default: '2.2.2'
  tgenv-version:
    description: 'Version of tgenv to install'
    required: false
    default: '0.1.0'
  aws-role-arn:
    description: 'AWS Role that will be assumed via github OIDC'
    required: false
    default: ''
  aws-default-region:
    description: 'AWS default region'
    required: false
    default: 'eu-central-1'
  aws-token-file:
    description: 'Path to AWS web identity token file'
    required: false
    default: '/tmp/awscreds'

runs:
  using: 'composite'
  steps:
    - name: Install terraform toolstack
      env:
        TFENV_VERSION: ${{ inputs.tfenv-version }}
        TGENV_VERSION: ${{ inputs.tgenv-version }}
      run: ${{ github.action_path }}/scripts/install_tftools.sh
      shell: bash
    
    - name: Configure OIDC web identity token file for AWS
      # We cannot use gh action conditionals here yet :(
      # https://github.com/actions/runner/issues/834
      env:
        AWS_ROLE_ARN: ${{ inputs.aws-role-arn}}
        AWS_WEB_IDENTITY_TOKEN_FILE: ${{ inputs.aws-token-file}}
        AWS_DEFAULT_REGION: ${{ inputs.aws-default-region}}
      run: ${{ github.action_path }}/scripts/configure_token.sh
      shell: bash
